sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  fast_finish: true
  include:
    - php: '7.3'
      env:
        - DEV="--no-dev"
    - php: '7.3'
      env:
        - TESTS=1
    - php: '7.4'
      env:
        - DEV="--no-dev"
    - php: '7.4'
      env:
        - SNIFF=1 TESTS=1 COVERAGE=1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - node_modules

before_script:
  - phpenv rehash
  - composer install $DEV
  - if [[ "$COVERAGE" == "1" ]]; then cd src; yarn install --ignore-engines; cd ..; fi

script:
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs --colors; fi
  - if [[ "$TESTS" == "1" ]]; then make update-phpunit; fi
  - if [[ "$TESTS" == "1" && "$COVERAGE" != "1" ]]; then vendor/phpunit/phpunit/phpunit --configuration tests/phpunit/phpunit.xml; fi
  - if [[ "$COVERAGE" == "1" ]]; then vendor/phpunit/phpunit/phpunit --configuration tests/phpunit/phpunit.xml --coverage-clover coverage.xml; fi
  - if [[ "$COVERAGE" == "1" ]]; then php vendor/php-coveralls/php-coveralls/bin/php-coveralls -v; fi